# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_video.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(781, 508)
        self.image_label = QtWidgets.QLabel(Form)
        self.image_label.setGeometry(QtCore.QRect(30, 20, 361, 291))
        self.image_label.setText("")
        self.image_label.setPixmap(QtGui.QPixmap("gui_images/cctvholder.png"))
        self.image_label.setScaledContents(True)
        self.image_label.setObjectName("image_label")
        self.streamControl = QtWidgets.QPushButton(Form)
        self.streamControl.setGeometry(QtCore.QRect(620, 430, 141, 61))
        self.streamControl.setObjectName("streamControl")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(30, 330, 141, 81))
        self.groupBox.setObjectName("groupBox")
        self.cameraID = QtWidgets.QLineEdit(self.groupBox)
        self.cameraID.setGeometry(QtCore.QRect(70, 30, 61, 21))
        self.cameraID.setObjectName("cameraID")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 30, 61, 16))
        self.label.setObjectName("label")
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setGeometry(QtCore.QRect(180, 330, 211, 81))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(20, 20, 47, 13))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(20, 50, 47, 13))
        self.label_3.setObjectName("label_3")
        self.chatID = QtWidgets.QLineEdit(self.groupBox_2)
        self.chatID.setGeometry(QtCore.QRect(80, 20, 113, 20))
        self.chatID.setObjectName("chatID")
        self.token = QtWidgets.QLineEdit(self.groupBox_2)
        self.token.setGeometry(QtCore.QRect(80, 50, 113, 20))
        self.token.setText("")
        self.token.setObjectName("token")
        self.groupBox_3 = QtWidgets.QGroupBox(Form)
        self.groupBox_3.setGeometry(QtCore.QRect(410, 20, 351, 391))
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox_3)
        self.label_4.setGeometry(QtCore.QRect(20, 30, 91, 21))
        self.label_4.setObjectName("label_4")
        self.id0 = QtWidgets.QLabel(self.groupBox_3)
        self.id0.setGeometry(QtCore.QRect(20, 100, 47, 13))
        self.id0.setText("")
        self.id0.setObjectName("id0")
        self.pp0 = QtWidgets.QLabel(self.groupBox_3)
        self.pp0.setGeometry(QtCore.QRect(20, 140, 81, 81))
        self.pp0.setText("")
        self.pp0.setPixmap(QtGui.QPixmap("gui_images/pp.jpeg"))
        self.pp0.setScaledContents(True)
        self.pp0.setObjectName("pp0")
        self.pp1 = QtWidgets.QLabel(self.groupBox_3)
        self.pp1.setGeometry(QtCore.QRect(130, 140, 81, 81))
        self.pp1.setText("")
        self.pp1.setPixmap(QtGui.QPixmap("gui_images/pp.jpeg"))
        self.pp1.setScaledContents(True)
        self.pp1.setObjectName("pp1")
        self.id1 = QtWidgets.QLabel(self.groupBox_3)
        self.id1.setGeometry(QtCore.QRect(130, 100, 47, 13))
        self.id1.setText("")
        self.id1.setObjectName("id1")
        self.pp2 = QtWidgets.QLabel(self.groupBox_3)
        self.pp2.setGeometry(QtCore.QRect(240, 140, 81, 81))
        self.pp2.setText("")
        self.pp2.setPixmap(QtGui.QPixmap("gui_images/pp.jpeg"))
        self.pp2.setScaledContents(True)
        self.pp2.setObjectName("pp2")
        self.id2 = QtWidgets.QLabel(self.groupBox_3)
        self.id2.setGeometry(QtCore.QRect(240, 100, 47, 13))
        self.id2.setText("")
        self.id2.setObjectName("id2")
        self.pp3 = QtWidgets.QLabel(self.groupBox_3)
        self.pp3.setGeometry(QtCore.QRect(20, 270, 81, 81))
        self.pp3.setText("")
        self.pp3.setPixmap(QtGui.QPixmap("gui_images/pp.jpeg"))
        self.pp3.setScaledContents(True)
        self.pp3.setObjectName("pp3")
        self.id3 = QtWidgets.QLabel(self.groupBox_3)
        self.id3.setGeometry(QtCore.QRect(20, 240, 47, 13))
        self.id3.setText("")
        self.id3.setObjectName("id3")
        self.pp4 = QtWidgets.QLabel(self.groupBox_3)
        self.pp4.setGeometry(QtCore.QRect(130, 270, 81, 81))
        self.pp4.setText("")
        self.pp4.setPixmap(QtGui.QPixmap("gui_images/pp.jpeg"))
        self.pp4.setScaledContents(True)
        self.pp4.setObjectName("pp4")
        self.id4 = QtWidgets.QLabel(self.groupBox_3)
        self.id4.setGeometry(QtCore.QRect(130, 240, 47, 13))
        self.id4.setText("")
        self.id4.setObjectName("id4")
        self.pp5 = QtWidgets.QLabel(self.groupBox_3)
        self.pp5.setGeometry(QtCore.QRect(240, 270, 81, 81))
        self.pp5.setText("")
        self.pp5.setPixmap(QtGui.QPixmap("gui_images/pp.jpeg"))
        self.pp5.setScaledContents(True)
        self.pp5.setObjectName("pp5")
        self.id5 = QtWidgets.QLabel(self.groupBox_3)
        self.id5.setGeometry(QtCore.QRect(240, 240, 47, 13))
        self.id5.setText("")
        self.id5.setObjectName("id5")
        self.totalCustomers = QtWidgets.QLabel(self.groupBox_3)
        self.totalCustomers.setGeometry(QtCore.QRect(130, 30, 47, 20))
        self.totalCustomers.setObjectName("totalCustomers")
        self.label_5 = QtWidgets.QLabel(self.groupBox_3)
        self.label_5.setGeometry(QtCore.QRect(20, 70, 91, 16))
        self.label_5.setObjectName("label_5")
        self.currentCustomers = QtWidgets.QLabel(self.groupBox_3)
        self.currentCustomers.setGeometry(QtCore.QRect(130, 70, 47, 13))
        self.currentCustomers.setObjectName("currentCustomers")
        self.label_6 = QtWidgets.QLabel(self.groupBox_3)
        self.label_6.setGeometry(QtCore.QRect(20, 120, 61, 16))
        self.label_6.setObjectName("label_6")
        self.mask0 = QtWidgets.QLabel(self.groupBox_3)
        self.mask0.setGeometry(QtCore.QRect(80, 120, 47, 16))
        self.mask0.setObjectName("mask0")
        self.mask1 = QtWidgets.QLabel(self.groupBox_3)
        self.mask1.setGeometry(QtCore.QRect(190, 120, 47, 16))
        self.mask1.setObjectName("mask1")
        self.label_9 = QtWidgets.QLabel(self.groupBox_3)
        self.label_9.setGeometry(QtCore.QRect(130, 120, 61, 16))
        self.label_9.setObjectName("label_9")
        self.mask2 = QtWidgets.QLabel(self.groupBox_3)
        self.mask2.setGeometry(QtCore.QRect(300, 120, 47, 16))
        self.mask2.setObjectName("mask2")
        self.label_11 = QtWidgets.QLabel(self.groupBox_3)
        self.label_11.setGeometry(QtCore.QRect(240, 120, 61, 16))
        self.label_11.setObjectName("label_11")
        self.mask3 = QtWidgets.QLabel(self.groupBox_3)
        self.mask3.setGeometry(QtCore.QRect(80, 250, 47, 16))
        self.mask3.setObjectName("mask3")
        self.label_13 = QtWidgets.QLabel(self.groupBox_3)
        self.label_13.setGeometry(QtCore.QRect(20, 250, 61, 16))
        self.label_13.setObjectName("label_13")
        self.mask4 = QtWidgets.QLabel(self.groupBox_3)
        self.mask4.setGeometry(QtCore.QRect(190, 250, 47, 16))
        self.mask4.setObjectName("mask4")
        self.label_15 = QtWidgets.QLabel(self.groupBox_3)
        self.label_15.setGeometry(QtCore.QRect(130, 250, 61, 16))
        self.label_15.setObjectName("label_15")
        self.mask5 = QtWidgets.QLabel(self.groupBox_3)
        self.mask5.setGeometry(QtCore.QRect(300, 250, 47, 16))
        self.mask5.setObjectName("mask5")
        self.label_17 = QtWidgets.QLabel(self.groupBox_3)
        self.label_17.setGeometry(QtCore.QRect(240, 250, 61, 16))
        self.label_17.setObjectName("label_17")
        self.groupBox_4 = QtWidgets.QGroupBox(Form)
        self.groupBox_4.setGeometry(QtCore.QRect(30, 420, 361, 71))
        self.groupBox_4.setObjectName("groupBox_4")
        self.gunCheckBox = QtWidgets.QRadioButton(self.groupBox_4)
        self.gunCheckBox.setGeometry(QtCore.QRect(10, 30, 82, 17))
        self.gunCheckBox.setObjectName("gunRadio")
        self.maskCheckBox = QtWidgets.QRadioButton(self.groupBox_4)
        self.maskCheckBox.setGeometry(QtCore.QRect(110, 30, 82, 17))
        self.maskCheckBox.setObjectName("maskRadio")
        self.gunMaskCheckBox = QtWidgets.QRadioButton(self.groupBox_4)
        self.gunMaskCheckBox.setGeometry(QtCore.QRect(210, 30, 141, 17))
        self.gunMaskCheckBox.setObjectName("gunMaskRadio")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "CCTV"))
        self.streamControl.setText(_translate("Form", "BAŞLAT"))
        self.groupBox.setTitle(_translate("Form", "Kamera Ayarı"))
        self.label.setText(_translate("Form", "Kamera ID"))
        self.groupBox_2.setTitle(_translate("Form", "Telegram Ayarları"))
        self.label_2.setText(_translate("Form", "Chat ID"))
        self.label_3.setText(_translate("Form", "Token"))
        self.groupBox_3.setTitle(_translate("Form", "Analiz Ekranı"))
        self.label_4.setText(_translate("Form", "Toplam kişi sayısı"))
        self.totalCustomers.setText(_translate("Form", "0"))
        self.label_5.setText(_translate("Form", "Anlık kişi sayısı"))
        self.currentCustomers.setText(_translate("Form", "0"))
        self.label_6.setText(_translate("Form", "Tıbbi Maske:"))
        self.mask0.setText(_translate("Form", "Yok"))
        self.mask1.setText(_translate("Form", "Yok"))
        self.label_9.setText(_translate("Form", "Tıbbi Maske:"))
        self.mask2.setText(_translate("Form", "Yok"))
        self.label_11.setText(_translate("Form", "Tıbbi Maske:"))
        self.mask3.setText(_translate("Form", "Yok"))
        self.label_13.setText(_translate("Form", "Tıbbi Maske:"))
        self.mask4.setText(_translate("Form", "Yok"))
        self.label_15.setText(_translate("Form", "Tıbbi Maske:"))
        self.mask5.setText(_translate("Form", "Yok"))
        self.label_17.setText(_translate("Form", "Tıbbi Maske:"))
        self.groupBox_4.setTitle(_translate("Form", "Nesne Tanıma Modelleri"))
        self.gunCheckBox.setText(_translate("Form", "Tabanca"))
        self.maskCheckBox.setText(_translate("Form", "Tıbbi Maske"))
        self.gunMaskCheckBox.setText(_translate("Form", "Tabanca ve Tıbbi Maske"))



